# -*- coding: utf-8 -*-
"""vegetable-recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100sQEbr7ZbF1AAG2wvmMg3Lhy0zOYSd6

Ladya Kalascha - CACC200D6X1654

# Klasifikasi Gambar Sayuran Menggunakan CNN

## Pendahuluan
Proyek ini mengimplementasikan **Convolutional Neural Network (CNN)** untuk mengklasifikasikan gambar sayuran ke dalam 15 kategori berbeda. Dataset yang digunakan terdiri dari lebih dari 10.000 gambar yang dibagi menjadi data pelatihan, validasi, dan pengujian.

### Tujuan
- Membangun dan melatih model CNN menggunakan Keras Sequential API
- Mencapai akurasi ≥95% pada data pelatihan dan pengujian
- Melakukan preprocessing gambar dengan data augmentation yang tepat
- Mengevaluasi performa model menggunakan visualisasi
- Mengonversi model terlatih ke berbagai format (SavedModel, TF-Lite, TFJS)
- Melakukan inferensi pada gambar sayuran nyata

### Informasi Dataset
- **Sumber:** Dataset Gambar Sayuran Lokal
- **Jumlah Kelas:** 15 jenis sayuran
- **Daftar Kelas:**  
  Bean, Bitter Gourd, Bottle Gourd, Brinjal, Broccoli,  
  Cabbage, Capsicum, Carrot, Cauliflower, Cucumber,  
  Papaya, Potato, Pumpkin, Radish, Tomato
- **Pembagian Dataset:**  
  - Train : 70%  
  - Validation : 15%  
  - Test : 15%
"""

import zipfile
import os

zip_file_path = '/content/Vegetable Images.zip'
extract_dir = '/content/'

if os.path.exists(zip_file_path):
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    print(f"Successfully unzipped '{zip_file_path}' to '{extract_dir}'")
else:
    print(f"Error: Zip file not found at '{zip_file_path}'")

print("Contents of extracted directory:")
print(os.listdir(os.path.join(extract_dir, 'Vegetable Images')))

"""# 1. Data Preparation

## 1.1 Import Required Libraries
"""

import os
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.applications import VGG16

try:
    import tensorflowjs
except ImportError:
    print("tensorflowjs not found, installing...")
    !pip install tensorflowjs
    !pip install --upgrade tensorflow
    import tensorflow as tf
    import tensorflowjs

print("TensorFlow version:", tf.__version__)
print("GPU Available:", len(tf.config.list_physical_devices('GPU')) > 0)

"""# Train & Test split"""

base_dir = Path('/content/Vegetable Images')
train_dir = base_dir / 'train'
test_dir = base_dir / 'test'
validation_dir = base_dir / 'validation'

print("Checking dataset structure...")
print(f"Train directory exists: {train_dir.exists()}")
print(f"Test directory exists: {test_dir.exists()}")
print(f"Validation directory exists: {validation_dir.exists()}")

classes = sorted([d.name for d in train_dir.iterdir() if d.is_dir()])
num_classes = len(classes)

print(f"\nNumber of classes: {num_classes}")
print(f"Classes: {classes}")

def count_images(directory):
    count = 0
    for class_dir in directory.iterdir():
        if class_dir.is_dir():
            count += len(list(class_dir.glob('*.*')))
    return count

train_count = count_images(train_dir)
test_count = count_images(test_dir)
val_count = count_images(validation_dir)

print(f"\nDataset Statistics:")
print(f"Training images: {train_count}")
print(f"Validation images: {val_count}")
print(f"Testing images: {test_count}")
print(f"Total images: {train_count + val_count + test_count}")

"""## 1.3 Data Preprocessing and Augmentation"""

IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32

print(f"Image size: {IMG_HEIGHT} x {IMG_WIDTH}")
print(f"Batch size: {BATCH_SIZE}")

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=False,
    fill_mode='nearest',
    brightness_range=[0.8, 1.2],
    shear_range=0.15
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    str(train_dir),
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

val_generator = val_test_datagen.flow_from_directory(
    str(validation_dir),
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False,
    seed=42
)

test_generator = val_test_datagen.flow_from_directory(
    str(test_dir),
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False,
    seed=42
)

class_labels = train_generator.class_indices
print(f"\nClass indices: {class_labels}")

"""## 1.4 Visualize Sample Images"""

fig, axes = plt.subplots(3, 5, figsize=(15, 9))
axes = axes.ravel()

for i in range(15):
    batch = next(train_generator)
    images, labels = batch

    img = images[0]
    label_idx = np.argmax(labels[0])
    label_name = list(class_labels.keys())[label_idx]

    axes[i].imshow(img)
    axes[i].set_title(f"{label_name}", fontsize=10)
    axes[i].axis('off')

plt.tight_layout()
plt.savefig('sample_images.png', dpi=100, bbox_inches='tight')
plt.show()

print("Sample images displayed (with augmentation)")

"""# 2. Model Building

## 2.1 Build CNN Architecture with Conv2D and MaxPooling
"""

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', padding='same',
                  input_shape=(IMG_HEIGHT, IMG_WIDTH, 3), name='conv_block1_1'),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same', name='conv_block1_2'),
    layers.MaxPooling2D((2, 2), name='pool_block1'),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3, 3), activation='relu', padding='same', name='conv_block2_1'),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same', name='conv_block2_2'),
    layers.MaxPooling2D((2, 2), name='pool_block2'),
    layers.Dropout(0.25),

    layers.Conv2D(128, (3, 3), activation='relu', padding='same', name='conv_block3_1'),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same', name='conv_block3_2'),
    layers.MaxPooling2D((2, 2), name='pool_block3'),
    layers.Dropout(0.25),

    layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv_block4_1'),
    layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv_block4_2'),
    layers.MaxPooling2D((2, 2), name='pool_block4'),
    layers.Dropout(0.25),

    layers.Flatten(name='flatten'),
    layers.Dense(512, activation='relu', name='dense1'),
    layers.Dropout(0.5),
    layers.Dense(256, activation='relu', name='dense2'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax', name='output')
])

print("Model Architecture:")
model.summary()

optimizer = Adam(learning_rate=0.0001)
model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("\nModel compiled successfully!")

"""## 2.2 Define Training Callbacks"""

callback_list = [
    ModelCheckpoint(
        filepath='best_model.h5',
        monitor='val_accuracy',
        save_best_only=True,
        mode='max',
        verbose=1
    ),

    EarlyStopping(
        monitor='val_accuracy',
        patience=20,
        restore_best_weights=True,
        verbose=1,
        min_delta=0.001
    ),

    ReduceLROnPlateau(
        monitor='val_accuracy',
        factor=0.5,
        patience=10,
        min_lr=1e-7,
        verbose=1
    )
]

print("Callbacks configured:")
print("✓ ModelCheckpoint - saves best model based on validation accuracy")
print("✓ EarlyStopping - stops training if val_accuracy doesn't improve for 20 epochs")
print("✓ ReduceLROnPlateau - reduces learning rate when accuracy plateaus")

"""## 2.3 Train the Model"""

steps_per_epoch = train_generator.samples // BATCH_SIZE
validation_steps = val_generator.samples // BATCH_SIZE

print(f"Steps per epoch: {steps_per_epoch}")
print(f"Validation steps: {validation_steps}")
print(f"\nStarting training...")
print(f"Total images in training: {train_generator.samples}")
print(f"Total images in validation: {val_generator.samples}")

history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    validation_data=val_generator,
    validation_steps=validation_steps,
    epochs=100,
    callbacks=callback_list,
    verbose=1
)

print("\nTraining completed!")

"""# 3. Model Evaluation and Visualization

## 3.1 Evaluate Model on Test Set
"""

loaded_best_model = tf.keras.models.load_model('best_model.h5')

train_loss, train_accuracy = loaded_best_model.evaluate(
    train_generator,
    steps=train_generator.samples // BATCH_SIZE,
    verbose=0
)

val_loss, val_accuracy = loaded_best_model.evaluate(
    val_generator,
    steps=val_generator.samples // BATCH_SIZE,
    verbose=0
)

test_loss, test_accuracy = loaded_best_model.evaluate(
    test_generator,
    steps=test_generator.samples // BATCH_SIZE,
    verbose=0
)

print("=" * 60)
print("MODEL EVALUATION RESULTS (Using best_model.h5)")
print("=" * 60)
print(f"Training   - Loss: {train_loss:.4f}, Accuracy: {train_accuracy*100:.2f}%")
print(f"Validation - Loss: {val_loss:.4f}, Accuracy: {val_accuracy*100:.2f}%")
print(f"Test       - Loss: {test_loss:.4f}, Accuracy: {test_accuracy*100:.2f}%")
print("=" * 60)

print("\n✓ CRITERIA CHECK:")
if train_accuracy >= 0.85 and test_accuracy >= 0.85:
    print("  ✅ Minimum 85% accuracy requirement: PASSED")
else:
    print("  ❌ Minimum 85% accuracy requirement: FAILED")

if train_accuracy >= 0.95 and test_accuracy >= 0.95:
    print("  ✅ Target 95% accuracy for high score: PASSED")
else:
    print("  ⚠️  Target 95% accuracy for high score: IN PROGRESS")

"""## 3.2 Plot Accuracy and Loss Curves"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['accuracy'], label='Training Accuracy', linewidth=2)
axes[0].plot(history.history['val_accuracy'], label='Validation Accuracy', linewidth=2)
axes[0].set_title('Model Accuracy', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Accuracy', fontsize=12)
axes[0].legend(fontsize=11)
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['loss'], label='Training Loss', linewidth=2)
axes[1].plot(history.history['val_loss'], label='Validation Loss', linewidth=2)
axes[1].set_title('Model Loss', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Loss', fontsize=12)
axes[1].legend(fontsize=11)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_history.png', dpi=300, bbox_inches='tight')
plt.show()

print("✓ Training history plots saved as 'training_history.png'")

"""## 3.3 Generate Predictions and Classification Report"""

from sklearn.metrics import classification_report, confusion_matrix
import sklearn

test_generator.reset()
predictions = loaded_best_model.predict(test_generator, verbose=0)
predicted_classes = np.argmax(predictions, axis=1)

true_classes = test_generator.classes

class_names = list(class_labels.keys())

print("=" * 80)
print("CLASSIFICATION REPORT (Test Set) - Using Best Model")
print("=" * 80)
print(classification_report(true_classes, predicted_classes, target_names=class_names, digits=4))

cm = confusion_matrix(true_classes, predicted_classes)

fig, ax = plt.subplots(figsize=(16, 14))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            ax=ax, cbar_kws={'label': 'Count'})
ax.set_title('Confusion Matrix - Test Set (Using Best Model)', fontsize=16, fontweight='bold')
ax.set_ylabel('True Label', fontsize=12)
ax.set_xlabel('Predicted Label', fontsize=12)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

print("✓ Confusion matrix saved as 'confusion_matrix.png'")

"""# 4. Model Conversion

## 4.1 Save Model as SavedModel Format
"""

output_dir = Path('model_outputs')
output_dir.mkdir(exist_ok=True)

savedmodel_dir = output_dir / 'saved_model'
tflite_dir = output_dir / 'tflite'
tfjs_dir = output_dir / 'tfjs_model'

print("Converting to SavedModel format...")
model.export(str(savedmodel_dir))
print(f"✓ SavedModel saved to: {savedmodel_dir}")

print("\nSavedModel directory structure:")
for root, dirs, files in os.walk(savedmodel_dir):
    level = root.replace(str(savedmodel_dir), '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    sub_indent = ' ' * 2 * (level + 1)
    for file in files[:5]:
        print(f'{sub_indent}{file}')

"""## 4.2 Convert Model to TensorFlow Lite (TF-Lite)"""

print("\nConverting to TensorFlow Lite format...")

converter = tf.lite.TFLiteConverter.from_saved_model(str(savedmodel_dir))
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS
]
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

tflite_dir.mkdir(exist_ok=True)
tflite_model_path = tflite_dir / 'model.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

print(f"✓ TF-Lite model saved to: {tflite_model_path}")
print(f"  Model size: {len(tflite_model) / 1024 / 1024:.2f} MB")

labels_path = tflite_dir / 'labels.txt'
with open(labels_path, 'w') as f:
    for class_name in class_names:
        f.write(class_name + '\n')

print(f"✓ Class labels saved to: {labels_path}")

"""## 4.3 Convert Model to TensorFlow.js (TFJS)"""

print("\nConverting to TensorFlow.js format...")

import subprocess

tfjs_dir.mkdir(exist_ok=True)

try:
    cmd = [
        'tensorflowjs_converter',
        '--input_format', 'tf_saved_model',
        str(savedmodel_dir),
        str(tfjs_dir)
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        print(f"✓ TFJS model saved to: {tfjs_dir}")

        print("\nTFJS directory contents:")
        for file in tfjs_dir.glob('*'):
            size_mb = file.stat().st_size / 1024 / 1024 if file.is_file() else 0
            print(f"  - {file.name} ({size_mb:.2f} MB)")
    else:
        print(f"⚠️  TFJS conversion note: {result.stderr}")

except Exception as e:
    print(f"⚠️  Note: TFJS conversion skipped (tensorflowjs package may need installation)")
    print(f"     Error: {str(e)}")

"""# 5. Inference

## 5.1 Load Trained Model and Perform Inference
"""

loaded_model = tf.keras.models.load_model('best_model.h5')

print("✓ Model loaded successfully")
print(f"Model shape: {loaded_model.input_shape}")

def predict_image(image_path, model, class_names, top_k=3):
    """
    Predict vegetable class from image
    """
    img = load_img(image_path, target_size=(IMG_HEIGHT, IMG_WIDTH))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    predictions = model.predict(img_array, verbose=0)
    predicted_class_idx = np.argmax(predictions[0])
    predicted_class = class_names[predicted_class_idx]
    confidence = predictions[0][predicted_class_idx] * 100

    top_indices = np.argsort(predictions[0])[-top_k:][::-1]
    top_predictions = [(class_names[idx], predictions[0][idx]*100) for idx in top_indices]

    return {
        'image': img,
        'predicted_class': predicted_class,
        'confidence': confidence,
        'top_predictions': top_predictions,
        'raw_predictions': predictions[0]
    }

print("✓ Prediction function ready")

"""## 5.2 Inference Examples on Test Images"""

import random

test_image_paths = []
for class_name in class_names:
    class_dir = test_dir / class_name
    for img_file in class_dir.glob('*.*'):
        test_image_paths.append(img_file)

sample_images = random.sample(test_image_paths, min(12, len(test_image_paths)))

results = [predict_image(str(img_path), loaded_model, class_names) for img_path in sample_images]

fig, axes = plt.subplots(3, 4, figsize=(16, 12))
axes = axes.ravel()

for idx, result in enumerate(results):
    axes[idx].imshow(result['image'])

    title = f"Pred: {result['predicted_class']}\nConfidence: {result['confidence']:.1f}%"
    color = 'green' if result['confidence'] > 80 else 'orange'

    axes[idx].set_title(title, fontsize=10, fontweight='bold', color=color)
    axes[idx].axis('off')

    top_preds = '\n'.join([f"{name}: {conf:.1f}%" for name, conf in result['top_predictions'][:3]])
    axes[idx].text(0.5, -0.1, top_preds, transform=axes[idx].transAxes,
                   fontsize=8, ha='center', va='top')

plt.tight_layout()
plt.savefig('inference_examples.png', dpi=300, bbox_inches='tight')
plt.show()

print("✓ Inference examples saved as 'inference_examples.png'")

"""## 5.3 Verify TF-Lite Model with Inference"""

try:
    interpreter = tf.lite.Interpreter(model_path=str(tflite_model_path))
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print("=" * 60)
    print("TF-LITE MODEL VERIFICATION")
    print("=" * 60)
    print(f"✓ TF-Lite model loaded successfully")
    print(f"\nInput Shape: {input_details[0]['shape']}")
    print(f"Output Shape: {output_details[0]['shape']}")

    test_img = load_img(str(sample_images[0]), target_size=(IMG_HEIGHT, IMG_WIDTH))
    test_array = img_to_array(test_img)
    test_array = np.expand_dims(test_array, axis=0)
    test_array = (test_array / 127.5 - 1).astype(np.float32)

    interpreter.set_tensor(input_details[0]['index'], test_array)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    predicted_idx = np.argmax(output[0])
    confidence = output[0][predicted_idx] * 100

    print(f"\n✓ TF-Lite Inference Test:")
    print(f"  Predicted Class: {class_names[predicted_idx]}")
    print(f"  Confidence: {confidence:.2f}%")
    print("=" * 60)

except Exception as e:
    print(f"⚠️  TF-Lite verification note: {str(e)}")

import shutil
import os

output_zip_path = 'model_outputs.zip'
shutil.make_archive(output_zip_path.replace('.zip', ''), 'zip', '/content/model_outputs')

print(f"Successfully created '{output_zip_path}' containing the content of '/content/model_outputs'")
print("You can now download this file from the Colab file browser (left sidebar > folder icon).")

"""# 📌 Kesimpulan

Proyek klasifikasi gambar sayuran menggunakan **Convolutional Neural Network (CNN)** ini berhasil dikembangkan dengan baik menggunakan TensorFlow dan Keras. Model mampu mempelajari pola visual dari berbagai jenis sayuran melalui proses training pada dataset yang terdiri dari lebih dari 10.000 gambar dan 15 kelas berbeda.

Beberapa tahapan penting seperti preprocessing data, data augmentation, pembuatan arsitektur CNN, proses training, evaluasi model, hingga inferensi berhasil diimplementasikan secara lengkap. Selain itu, performa model juga dianalisis menggunakan visualisasi accuracy, loss, confusion matrix, dan contoh prediksi gambar sehingga hasil pelatihan dapat dipahami dengan lebih jelas.

### Poin-Poin Hasil Proyek
- Dataset berhasil dibagi menjadi train, validation, dan test set dengan rasio 70:15:15
- Model CNN dibangun menggunakan layer Conv2D, MaxPooling2D, Flatten, dan Dense
- Data augmentation digunakan untuk meningkatkan generalisasi model
- Callback seperti EarlyStopping dan ReduceLROnPlateau berhasil membantu proses training menjadi lebih optimal
- Model berhasil diekspor ke beberapa format:
  - SavedModel
  - TensorFlow Lite (TFLite)
  - TensorFlow.js (TFJS)
- Evaluasi model dilakukan menggunakan grafik accuracy/loss dan confusion matrix
- Model dapat melakukan prediksi pada gambar sayuran baru dengan baik

Secara keseluruhan, proyek ini menunjukkan bahwa metode CNN sangat efektif untuk tugas klasifikasi citra, khususnya dalam mengenali berbagai jenis sayuran. Implementasi multi-format model juga membuat hasil proyek lebih fleksibel untuk digunakan pada berbagai platform seperti web, mobile, maupun deployment berbasis TensorFlow.
"""